[debug] ----------------------------------------------------------------------
[debug] Command:      /usr/local/Cellar/node/10.4.0/bin/node /usr/local/bin/firebase deploy
[debug] CLI Version:  3.0.7
[debug] Platform:     darwin
[debug] Node Version: v10.4.0
[debug] Time:         Thu Dec 27 2018 19:39:12 GMT+0000 (Greenwich Mean Time)
[debug] ----------------------------------------------------------------------
[debug] 
[debug] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/flight-club-f837c 
[debug] <<< HTTP RESPONSE 200
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/flight-club-f837c/tokens 
[debug] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'flight-club-f837c'...
[info] 
[info] i  deploying database, hosting
[info] ✔  database: rules ready to deploy.
[info] i  hosting: preparing build directory for upload...
[debug] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/flight-club-f837c/uploads/-LUlANxkc8ESWjorB0_U?fileCount=9&message= 
[debug] <<< HTTP RESPONSE 410
[debug] <<< HTTP RESPONSE BODY undefined
[debug] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:36:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: An unexpected error has occurred.
[debug] ----------------------------------------------------------------------
[debug] Command:      /usr/local/Cellar/node/10.4.0/bin/node /usr/local/bin/firebase deploy
[debug] CLI Version:  3.0.7
[debug] Platform:     darwin
[debug] Node Version: v10.4.0
[debug] Time:         Thu Dec 27 2018 19:40:49 GMT+0000 (Greenwich Mean Time)
[debug] ----------------------------------------------------------------------
[debug] 
[debug] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase"]
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/flight-club-f837c 
[debug] <<< HTTP RESPONSE 200
[debug] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/flight-club-f837c/tokens 
[debug] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'flight-club-f837c'...
[info] 
[info] i  deploying database, hosting
[info] ✔  database: rules ready to deploy.
[info] i  hosting: preparing build directory for upload...
[debug] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/flight-club-f837c/uploads/-LUlAkeItU5HdM-vV9fm?fileCount=9&message= 
[debug] <<< HTTP RESPONSE 410
[debug] <<< HTTP RESPONSE BODY undefined
[debug] TypeError: Cannot read property 'error' of undefined
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:10:13)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:36:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: An unexpected error has occurred.
